# set the base image
#Stage1
FROM node:12.18.2 as build
# set working directory
# this is the working folder in the container
# from which the app will be running from
WORKDIR /app
# copy everything to /app directory
# as opposed to on dev, in prod everything is copied to docker
COPY package.json /app 
RUN npm install
COPY . .
RUN npm run build


FROM nginx
COPY --from=build /app/build /usr/share/nginx/html

