# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: "3.7"

#Define services
services:  #Front-end react js Application
  fanatiqa-ui:
    stdin_open: true
    tty: true
    build: 
      context: ./fanatiqa-frontend
      dockerfile: ./Dockerfile.dev
    container_name: fanatiqa-ui
    ports:
      - "3000:3000"
    volumes: 
      - ./fanatiqa-frontend/src:/app/src:ro
    environment:
      - REACT_APP_NAME=PAVITRA-APP
      - CHOKIDAR_POLLING=true #only for windows even using powershell
    #one can also pass env file path using below declaaration
    #env_file:
    #  - ./.env

